name: docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Listuser
        run: whoami
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://hub.docker.com
          username: "srirammaster"
          password: "Sriram@99"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: employee:latest
